### ISSUE TITLE
Error occurred when fetching containers

### ISSUE THREAD

**Issue by psukys** [gpouilloux/gnome-shell-extension-docker#10]
After installing the GNOME extension, the extension's dropdown menu shows only this menu item.

Using: 

- Fedora 25, 
- GNOME 3.22.2
- Docker version 17.03.0-ce, build 60ccb22

**Comment by gpouilloux** [comment]
If you reached the `Error occurred when fetching containers` message, the good news is that the Docker binary is in your path and the daemon is running but the `docker ps` command fails.

Try to run this command line in your terminal:
`docker ps -a --format '{{.Names}},{{.Status}}'` but according to the error message it should fail.

**Comment by psukys** [comment]
Thank you, it seems that docker is not automatically starting. I resolved this by enabling systemd loading for docker.

**Comment by prosperoking** [comment]
I have the same issue but docker ps is working properly

**Comment by qsolutions-pl** [comment]
Same here, ubuntu 19.04 beta
