### ISSUE TITLE
Use a symbolic icon

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gpouilloux/gnome-shell-extension-docker#12]
Can you please a symbolic icon instead of a normal SVG one? The symbolic icons are themeable using CSS

**Comment by gpouilloux** [comment]
Don't have time to work on this. Feel free to submit a PR if you absolutely want this feature.

**Comment by gpouilloux** [comment]
Fixed by https://github.com/gpouilloux/gnome-shell-extension-docker/pull/15
