### ISSUE TITLE
Possible feature request (docker exec)

### ISSUE THREAD

**Issue by billiam13s** [gpouilloux/gnome-shell-extension-docker#14]
It will be nice to open terminal with the selected container then able to run command.

awesome work by the way.

**Comment by gpouilloux** [comment]
It'd be a great feature, for sure!
There's a WIP in this PR: https://github.com/gpouilloux/gnome-shell-extension-docker/pull/17

I believe that the best implementation would be to use the gjs Vte.Terminal class (see https://www.roojs.org/seed/gir-1.2-gtk-3.0/gjs/Vte.Terminal.html)

**Comment by thawkins** [comment]
@gpouilloux 
Can we have an option to turn that off and just use the gnome or system configured terminal

**Comment by gpouilloux** [comment]
Release 11 has been rolled-out : https://github.com/gpouilloux/gnome-shell-extension-docker/releases/tag/11
Please give a try
