### ISSUE TITLE
Wrong names

### ISSUE THREAD

**Issue by stefaca** [gpouilloux/gnome-shell-extension-docker#18]
I have debian:testing image but extension sees it like 'jolly_wright'. Is there any solution to see actual name?

**Comment by jrabbit** [comment]
That's the actual name of the container. you're looking to see the image type

**Comment by stefaca** [comment]
My bad. Yes :) Is there any solution to see it?

**Comment by ziggy42** [comment]
@stefaca the solution is to name your container. See https://docs.docker.com/engine/reference/run/

**Comment by stefaca** [comment]
Yes, that is the thing that will do my job. Thanks a lot. Can we close this issue? Actually, there is no issue but my non well known of docker :(
