### ISSUE TITLE
Feature request: docker exec -it <image_id>

### ISSUE THREAD

**Issue by sethwoodworth** [gpouilloux/gnome-shell-extension-docker#24]
As requested by thawkins on the gnome extension page:
> It would be great if you could add a "shell" command for running containers that would run docker exec -it [container] [shell command] ie docker exec -it mycontainer /bin/bash to open a bash shell on the running container, it may need some way to specify both the terminal prog and the shell command. 

I think this feature also sounds really helpful!

**Comment by thawkins** [comment]
Just checking in, i would help but i'm not big on JS, im more a java/kotlin man

**Comment by gpouilloux** [comment]
Release 11 has been rolled-out : https://github.com/gpouilloux/gnome-shell-extension-docker/releases/tag/11
Please give a try
