### ISSUE TITLE
Error: no property 'gicon' in property list (or its value was undefined). TypeError:  _indicator is undefined

### ISSUE THREAD

**Issue by kbaikov** [gpouilloux/gnome-shell-extension-docker#3]
Extention gives me this error in looking glass: 

"Error: no property 'gicon' in property list (or its value was undefined). TypeError:  _indicator is undefined"
And extention list in firefox shows just an error icon.

I have opensuse tumbleweed and gnome 3.20.2

Can you fix that?
Do you need any other info?
Thank you!

**Comment by Lerentis** [comment]
Having the same issue on Arch running gnome 3.20.2 as well.
I thing gnome made some changes is the latest update. Loved the extension thou. would be sad to not have it anymore :/

**Comment by gpouilloux** [comment]
Thanks for submitting this bug.
Unfortunately, I was not able to reproduce this bug using Gnome 3.20.2 and Arch.

Don't know if it's a bug with Gnome but if it happens again, feel free to ping me again.

I'm glad you find this extension useful

**Comment by kbaikov** [comment]
Gnome packages were updated in my distribution and the issue is gone.
Extension works as expected. Please feel free to close the issue.
