### ISSUE TITLE
gnome-shell -version Gnome Shell 3.28.3 , which version to use ( no 3.28 listed )

### ISSUE THREAD

**Issue by gt789** [gpouilloux/gnome-shell-extension-docker#35]
Hi I am trying to install it on ubuntu 18.04.
My Gnome Shell version is 3.28.3.
Installation link doesn't have 3.28 extension ( 3.22 and below ). Any hint/advice which one should I use in absence of 3.26 ( 322 , 3.20 ?)
Thanks in advance

**Comment by gpouilloux** [comment]
Hi @gt789 ,
I just uploaded a new version in the Gnome Extensions website : https://extensions.gnome.org/review/10174
