### ISSUE TITLE
Request: please tag releases on GitHub

### ISSUE THREAD

**Issue by jonafato** [gpouilloux/gnome-shell-extension-docker#37]
I'm working on packaging this extension for [NixOS](https://github.com/nixos/nixpkgs). Currently, there are no versioned release tags that I can point to in the build. Can you tag releases on GitHub so this information is readily available, both for this package and generally to be able to know what git revision corresponds to a release pushed to the GNOME extensions website? Thanks in advance!

**Comment by LevinGermann** [comment]
Because you're talking about NixOS, please be aware of this issue:
https://github.com/gpouilloux/gnome-shell-extension-docker/issues/39

**Comment by jonafato** [comment]
@LevinGermann Thanks for the heads up. I have a nix expression that accounts for this, which is in part why it specifically needs nixpkgs packaging rather than just copying a zip file.

**Comment by gpouilloux** [comment]
Good point!
I added a tag **10** for the latest release I uploaded in Gnome Extensions website.
