### ISSUE TITLE
Not working after upgrading gnome shell to 3.21.90

### ISSUE THREAD

**Issue by StanSvec** [gpouilloux/gnome-shell-extension-docker#4]
Hi Guillaume,

Can you please upgrade to the new gnome shell version?

**Comment by gpouilloux** [comment]
Hi StanSvec,

This extension currently supports Gnome Shell 3.18 and 3.20 (see https://github.com/gpouilloux/gnome-shell-extension-docker/blob/master/metadata.json#L4)
Basically, it's the versions on which I was able to test the extension.

Are you sure you upgraded to 3.12.90 ? Seems like an old version (if it exists)

In the meantime, to have the extension up and running, you can edit the metadata.json by yourself and add the version number 3.12.90 in the `shell-version` entry.

Guillaume

**Comment by StanSvec** [comment]
I'm sorry. I have no idea how I went to the version mentioned in the title. It should have been: **3.21.90**
I tried to edit metadata.json file, but it didn't help:
```
{
  "_generated": "Generated by SweetTooth, do not edit", 
  "description": "Print details about running containers", 
  "name": "docker-status", 
  "shell-version": [
    "3.18", 
    "3.20",
    "3.21.90"
  ], 
  "url": "", 
  "uuid": "docker_status@gpouilloux", 
  "version": 2
}
```

Any other idea pls?

Stan

**Comment by StanSvec** [comment]
It's working again after the last system update.
