### ISSUE TITLE
Version 10 not working with Gnome 3.22.2 (Debian Stretch)

### ISSUE THREAD

**Issue by meden** [gpouilloux/gnome-shell-extension-docker#44]
Upgrading to version 10 using `extensions.gnome.org` results in a non-functional extension (not even shown), but no error raised.

Manually downloading the version 9 and installing it using the gnome-tweaks-tool fails with the error "Invalid extension".

Thanks for you work!

**Comment by gsiciliano** [comment]
Same for me. Using ubuntu 19.04 with gnome 3.32, no errors given when activate extension, but no icon is shown

**Comment by dan-rally** [comment]
I also have this issue running on stock Ubuntu 19.04. Many thanks for a great extension.

**Comment by naXa777** [comment]
Not working in GNOME 3.32.1 / Ubuntu 19.04 when installing from https://extensions.gnome.org/extension/1065/docker-status/

**Comment by gpouilloux** [comment]
Hi,

I have strong feeling that this issue will be fixed as soon as we merge this pull request (See #48)

Stay tuned,

**Comment by gpouilloux** [comment]
Release 11 has been rolled-out : https://github.com/gpouilloux/gnome-shell-extension-docker/releases/tag/11
Please give a try
