### ISSUE TITLE
Extension not working in Ubuntu 19.04

### ISSUE THREAD

**Issue by cccaballero** [gpouilloux/gnome-shell-extension-docker#45]
Using Ubuntu 19.04 (Gnome 3.32.1) the extension does not appear in the top bar

**Comment by gpouilloux** [comment]
Hi @cccaballero 

I have strong feeling that this issue will be fixed as soon as we merge this pull request (See #48)

Stay tuned,

**Comment by gpouilloux** [comment]
Release 11 has been rolled-out : https://github.com/gpouilloux/gnome-shell-extension-docker/releases/tag/11
Please give a try
