### ISSUE TITLE
Not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by aristar** [gpouilloux/gnome-shell-extension-docker#49]
Ubuntu 20.04
Gnome 3.36.1
JS ERROR: Extension docker_status@gpouilloux: Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GOb>
                                                  DockerMenu_DockerMenu@/home/aaa/.local/share/gnome-shell/extensions/docker_status@gpouilloux/src/dockerMenu.js:32:49
                                                  enable@/home/aaa/.local/share/gnome-shell/extensions/docker_status@gpouilloux/extension.js:35:18
                                                  _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
                                                  loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:336:26
                                                  callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:39
                                                  gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13

**Comment by gpouilloux** [comment]
Hi @aristar ,

I have good feeling that this issue will be fixed as soon as we merge this pull request (See https://github.com/gpouilloux/gnome-shell-extension-docker/pull/48)

Stay tuned,

**Comment by gpouilloux** [comment]
Release 11 has been rolled-out : https://github.com/gpouilloux/gnome-shell-extension-docker/releases/tag/11
Please give a try
