### ISSUE TITLE
Is the extension up-to-date ?

### ISSUE THREAD

**Issue by tseho** [gpouilloux/gnome-shell-extension-docker#5]
After upgrading to gnome-shell 3.20, the extension loaded from [https://extensions.gnome.org/extension/1065/docker-status/](https://extensions.gnome.org/extension/1065/docker-status/) was broken because of the undefined 'gicon' bug. This has been fixed by c4e75fc, I manually applied the patch and it's working now.

Could you update the version on extensions.gnome.org ?

**Comment by gpouilloux** [comment]
Thanks for pointing this out.
I just updated the version on Gnome extensions
