### ISSUE TITLE
Favourite list loads with delay

### ISSUE THREAD

**Issue by vnagara** [gpouilloux/gnome-shell-extension-docker#55]
I wanted to reload gnome shell and wrote `killall gnome-shell` command. It destroyed the session and lead to a new login. After that the Docker loads empty after login and loads items after 15-25 seconds. With another user items loads immediately. Removing all files from my user home dir doesn't change anything.
Even don't know where can remain an attachment to my user in system.
![Screenshot from 2020-05-19 12-51-20-2-2](https://user-images.githubusercontent.com/1571419/82323806-7d244e00-99d0-11ea-9e31-4e205a4f590c.png)
After 20 seconds
![Screenshot from 2020-05-19 12-51-41-2-2](https://user-images.githubusercontent.com/1571419/82323819-84e3f280-99d0-11ea-955b-b47c286d355d.png)

**Comment by alessandrodolci** [comment]
Hello, I'm having troubles understanding your issue, are you sure it's something related to this extension?
If I'm getting it correctly, your dock is populating with a noticeable delay after a Gnome Shell restart, but I can't see any possible connection with the extension, let alone with the Docker service itself. Could you maybe clarify this a bit further?
Thank you.

**Comment by vnagara** [comment]
@alessandrodolci, Hi, it definitely loads with a delay that I can even take a screenshot. It is easy reproducable with the life CD of ubuntu 20.04. You need to chose gnome in wayland mode on login screen. The another user didn't have the issue as it used X11 system. I switched to Xorg because of this bag.
  Thanks.

**Comment by alessandrodolci** [comment]
I'm sorry, but I still can't see how this could be in some way related to this gnome-shell extension.
I tried on my 20.04 Ubuntu, with a Wayland session, but still can't find any evidence of your problem.

Keep in mind that, differently from what happens using Xorg, killing the gnome-shell process under Wayland means shutting down and restarting the entire graphical server, as well as the user session. This is probably causing issues with the icons dock itself.
Googling a bit your issue I noted several matches within the Ubuntu Dock extension, which is installed by default, as well as Dash to Dock and Dash to Panel. Have a look here: https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1869572

**Comment by vnagara** [comment]
Hi, thanks for your attention. Seems I reported to wrong program. That links seems is the same bug (I wonder how didn't I found it before as I googled).

**Comment by alessandrodolci** [comment]
No problem, I hope you'll manage to solve your issue!
