### ISSUE TITLE
problem launch shell

### ISSUE THREAD

**Issue by x0rld** [gpouilloux/gnome-shell-extension-docker#65]
When I click on open shell my terminal is open but close instantly
there is these log in `journalctl /usr/bin/gnome-shell -f`
i'm on fedora 33 with GNOME Shell 3.38.4
```
avril 09 20:49:09 fedora gnome-shell[2010]: Docker: `Open shell` action terminated successfully
avril 09 20:49:15 fedora gnome-shell[2010]: Usage of object.actor is deprecated for DockerMenu
                                            get@resource:///org/gnome/shell/ui/environment.js:317:29
                                            _renderMenu@/home/x0rld/.local/share/gnome-shell/extensions/docker_status@gpouilloux/src/dockerMenu.js:74:9
                                            _refreshMenu@/home/x0rld/.local/share/gnome-shell/extensions/docker_status@gpouilloux/src/dockerMenu.js:55:18
```

**Comment by alessandrodolci** [comment]
Hello,

I suspect your Docker container doesn't have shell binaries at `/bin/bash` or `/bin/sh`. Could you please check it out? You may have to customize your Dockerfile to add support for a shell.

As for the warnings, it's something we're aware of, but I'm afraid it doesn't relate to your problem.

**Comment by x0rld** [comment]
I have /bin/bash in the docker, I can access to the shell with docker exec -it

**Comment by alessandrodolci** [comment]
I made some tests using your configuration (3.38.4 on Fedora 33), everything seems ok to me. I tried running a shell inside a `redis:latest` container and it correctly brings up a new terminal.
 
Just to be sure, check that `gnome-terminal` is installed on your system and that the `SHELL` env variable is correctly set with your user's login shell.

**Comment by x0rld** [comment]
I have gnome-terminal and $SHELL set it's weird

**Comment by alessandrodolci** [comment]
Maybe you could provide us with some more detailed information about your configuration and use case, so that I can try and dig deeper into the issue?

Thank you.

**Comment by dhlbrg** [comment]
I'm experiencing the same issue. 
GNOME Shell 3.38.4 and Pop OS 21.04. I have gnome-terminal installed. But i am using fish as my shell, could that be the issue?

**Comment by alessandrodolci** [comment]
Hi @dubbe, just to confirm, is your `SHELL` environment variable set with the correct path to the fish binary?

**Comment by dhlbrg** [comment]
@alessandrodolci yes, it is

**Comment by alessandrodolci** [comment]
Are you sure that your container provides a shell? Check that either `docker exec -it <container-name> /bin/bash` or `docker exec -it <container-name> /bin/sh` are working.

**Comment by dhlbrg** [comment]
yes, those are both working fine.

**Comment by dhlbrg** [comment]
I see, just as @x0rld that the terminal opens briefly, but to fast to see any output
