### ISSUE TITLE
Fedora 25 (Gnome 3.22) support

### ISSUE THREAD

**Issue by cstoehr** [gpouilloux/gnome-shell-extension-docker#7]
Is the a plan to support the Gnome 3.22?

Cheers

**Comment by gpouilloux** [comment]
Just updated my system to Gnome Shell 3.22 and looks like the extension is supported.
I updated the version on [extensions.gnome.org](https://extensions.gnome.org/extension/1065/docker-status/)

Give it a try and let me know if you get any issues

**Comment by cstoehr** [comment]
works fine...your extention is great...thank you....good job
